### ISSUE TITLE
Font baking issue.

### ISSUE THREAD

**Issue by DampireX** [Immediate-Mode-UI/Nuklear#855]
Seems like a font baking via stbtt is quite broken. This is how looks the default font with default settings on SDL3 on GPU side. Custom TTF fonts looks the same - unnecessary wide.
<img width="1080" height="202" alt="Image" src="https://github.com/user-attachments/assets/514f999b-aafb-4f47-935b-1540565e13ae" />

**Comment by DampireX** [comment]
For an unknown reason nk_font_config::oversample_h is 3 while nk_font_config::oversample_v is 1. After specifying it manually texture is crisp and clear. Renderer is still blurred, but I've just fixed it through fixing text metrics to int. 
```c
        /* calculate and draw glyph drawing rectangle and image */
        gx = x + int(g.offset.x);
        gy = rect.y + int(g.offset.y);
        gw = int(g.width); gh = int(g.height);
        char_width = int(g.xadvance);
        nk_draw_list_push_rect_uv(list, nk_vec2(gx,gy), nk_vec2(gx + gw, gy+ gh),
            g.uv[0], g.uv[1], fg);
```

**Comment by sleeptightAnsiC** [comment]
Hah, I remember hitting this some time ago, and was wondering if this is a bug or some rendering trick. I still have a screenshot of it from that exact moment. Thanks for reporting this.

<img width="1185" height="363" alt="Image" src="https://github.com/user-attachments/assets/d7cffc90-f3a8-4d0b-a0c2-7406b8a416fc" />

**Comment by DampireX** [comment]
I wonder why all layout engine is not pixel perfect. It will fix any blurring artifacts and even simplistic AA approach of stbtt font rasterizer will look like okay.

**Comment by RobLoach** [comment]
> I wonder why all layout engine is not pixel perfect

I think this could be because of the non-`math.h` cos and sin functions. Try enabled `m`, and see if it works better 🫠 .... Hope to clean those up one day.

**Comment by sleeptightAnsiC** [comment]
(few notes for my future self)

Oversampling was probably used here as naive way of dealing with HiDPI, and maybe in order to tweak some badly behaving fonts. Example: https://github.com/Immediate-Mode-UI/Nuklear/commit/62ff1861a461691f3a6307fecc2b9789ecc109d8 and https://github.com/Immediate-Mode-UI/Nuklear/commit/ec4aa9992f8bd13dce8197ee8795071baa512c49

Some demos are dealing with this problem by manipulating font's scale - see https://github.com/Immediate-Mode-UI/Nuklear/pull/427 - I always found it a bit weird. Maybe it's not entirely correct.

~~The defaults are here - [src/nuklear_font.c#L868-L869](https://github.com/Immediate-Mode-UI/Nuklear/blob/50853aa65b5c818d02cfeff5e917bfc7b7bd9621/src/nuklear_font.c#L868-L869) - I haven't checked their history yet (Github doesn't allow for git-blame'ing our amalgamation because it's too big; I'll try again later by hand)~~ EDIT: see next comment

Our wikies suggest setting these values to `1` on your own. See [wiki/UTF-8-Support](https://github.com/Immediate-Mode-UI/Nuklear/wiki/UTF-8-Support#:~:text=config%2Eoversample%5Fh%20%3D%201%3B%20config%2Eoversample%5Fv%20%3D%201%3B) and [wiki/Complete-font-guide](https://github.com/Immediate-Mode-UI/Nuklear/wiki/Complete-font-guide#:~:text=cfg%5Flatin%2Eoversample%5Fh%20%3D%20cfg%5Flatin%2Eoversample%5Fv%20%3D%201%3B%20cfg%5Ficons%2Eoversample%5Fh%20%3D%20cfg%5Ficons%2Eoversample%5Fv%20%3D%201%3B%20cfg%5Fjapan%2Eoversample%5Fh%20%3D%20cfg%5Fjapan%2Eoversample%5Fv%20%3D%201%3B%20cfg%5Flatin)

STB upstream discourages oversampling, unless there is a very good reason to do so. Examples: https://github.com/nothings/stb/issues/648 / [stb_truetype.h#L636-L649](https://github.com/nothings/stb/blob/31c1ad37456438565541f4919958214b6e762fb4/stb_truetype.h#L636-L649) / [stb/blob/master/tests/oversample/README.md](https://github.com/nothings/stb/blob/master/tests/oversample/README.md)

**Comment by sleeptightAnsiC** [comment]
> The defaults are here - [src/nuklear_font.c#L868-L869](https://github.com/Immediate-Mode-UI/Nuklear/blob/50853aa65b5c818d02cfeff5e917bfc7b7bd9621/src/nuklear_font.c#L868-L869) - I haven't checked their history yet

git-blame showed me this: https://github.com/Immediate-Mode-UI/Nuklear/commit/1d7f0244f97e2d35a57bc90586863ab89bea9be3
bottom of the log says: _`In addition I oversampled the default font to make it look better.`_

I suspect it was some kind of misuse/hack given what the the rest of that commit was doing. If the intent was to **_only_** oversample the default built-in font, it makes no sense for nk_font_config to do this for every single one of them.

I have an idea on how to fix it. Just need to make sure it doesn't break anything.

**Comment by sleeptightAnsiC** [comment]
@DampireX 
> Renderer is still blurred, but I've just fixed it through fixing text metrics to int.

Blind guess: setting this nk_font_config's option to true by hand may help:
https://github.com/Immediate-Mode-UI/Nuklear/blob/e634a0dfa1b235a45a09a6d09d78b59af663f2e3/src/nuklear.h#L4082

Another guess: font's texture could use different filtering. For SDL_Renderer, the default one is `SDL_SCALEMODE_LINEAR`, but `SDL_SCALEMODE_NEAREST` might be better for small pixelated fonts. Other rendering APIs have a different name for this.

Changing text metrics to int is probably not a very good idea and most likely only works in your specific case.
